/**
 * Household join codes.
 *
 * Codes are 6 characters from [A-Z0-9] generated by the database (CSPRNG,
 * alphabet excludes 0/O/1/I). Anyone holding the code can join the household
 * through the join_by_code RPC - share it directly or via the invite link.
 */

export const JOIN_CODE_LENGTH = 6;

const JOIN_CODE_PATTERN = /^[A-Z0-9]{6}$/;

/** Strips separators, uppercases and truncates to a valid code shape. */
export function normalizeJoinCode(raw: string): string {
  return raw.replace(/[^a-zA-Z0-9]/g, '').toUpperCase().slice(0, JOIN_CODE_LENGTH);
}

export function isValidJoinCode(raw: string): boolean {
  return JOIN_CODE_PATTERN.test(normalizeJoinCode(raw));
}

/** Builds the shareable link: <origin>/onboarding?join=CODE */
export function buildJoinLink(origin: string, code: string): string {
  const normalizedOrigin = origin.replace(/\/+$/, '');
  return `${normalizedOrigin}/onboarding?join=${normalizeJoinCode(code)}`;
}
